const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Behaviors.Timer,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.ScriptsInEvents.FolhaDeEventoFase1_Event6_Act3,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.ScriptsInEvents.FolhaDeEventoFase2_Event5_Act3,
		C3.Behaviors.Timer.Cnds.OnTimer
	];
};
self.C3_JsPropNameTable = [
	{STOPPED: 0},
	{JUMP: 0},
	{Plataforma: 0},
	{Sólido: 0},
	{RUN: 0},
	{chãoinvisivel: 0},
	{L: 0},
	{Teclado: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{telapreta: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{FonteDeSprites: 0},
	{Sprite5: 0},
	{REINICIAR: 0},
	{TENTA: 0},
	{Sprite9: 0},
	{Sprite6: 0},
	{DEBUG: 0},
	{planoDeFundaFase2: 0},
	{Sprite7: 0},
	{Projétil: 0},
	{ESPECTRO: 0},
	{Sprite8: 0},
	{ESPECTRO3: 0},
	{Sprite10: 0},
	{ESPADA: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{tudoUnido: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite11: 0},
	{Cronômetro: 0},
	{timer: 0},
	{PLANODEFUNDOFASE2: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{FonteDeSprites2: 0},
	{FonteDeSprites3: 0},
	{Texto: 0},
	{Texto2: 0},
	{Luzdestruida: 0}
];

self.InstanceType = {
	STOPPED: class extends self.ISpriteInstance {},
	JUMP: class extends self.ISpriteInstance {},
	RUN: class extends self.ISpriteInstance {},
	chãoinvisivel: class extends self.ISpriteInstance {},
	L: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	telapreta: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	REINICIAR: class extends self.ISpriteInstance {},
	TENTA: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	DEBUG: class extends self.ITextInstance {},
	planoDeFundaFase2: class extends self.ITiledBackgroundInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	ESPECTRO: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	ESPECTRO3: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	ESPADA: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	tudoUnido: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	timer: class extends self.ISpriteInstance {},
	PLANODEFUNDOFASE2: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	FonteDeSprites2: class extends self.ISpriteFontInstance {},
	FonteDeSprites3: class extends self.ISpriteFontInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {}
}